jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('DBT_ENV_SECRET_DEV_KEYFILE') }}"
      project: "{{ env_var('DBT_ENV_SECRET_DEV_PROJECT') }}"
      dataset: "{{ env_var('DBT_ENV_SECRET_DEV_DATASET') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
